//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTaskSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public int id { get; set; }
        public Nullable<int> priority { get; set; }
        public string nameCustomer { get; set; }
        public string description { get; set; }
        public string dateDone { get; set; }
        public Nullable<bool> done { get; set; }
    }
}
