//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class convention
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public convention()
        {
            this.ConventionLog = new HashSet<ConventionLog>();
            this.customerComputerLog = new HashSet<customerComputerLog>();
            this.customerComputerLog1 = new HashSet<customerComputerLog>();
            this.TakhsisTabletAndClientToConvention = new HashSet<TakhsisTabletAndClientToConvention>();
            this.task = new HashSet<task>();
        }
    
        public int conventionID { get; set; }
        public string registerDate { get; set; }
        public string startDate { get; set; }
        public string comment { get; set; }
        public Nullable<int> companyID { get; set; }
        public string endDate { get; set; }
        public Nullable<int> countOfSystem { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ConventionInvoiceID { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual conventionDuration conventionDuration { get; set; }
        public virtual conventionType conventionType { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConventionLog> ConventionLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerComputerLog> customerComputerLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerComputerLog> customerComputerLog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakhsisTabletAndClientToConvention> TakhsisTabletAndClientToConvention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> task { get; set; }
    }
}
