//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTablets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerTablets()
        {
            this.TakhsisTabletAndClientToConvention = new HashSet<TakhsisTabletAndClientToConvention>();
        }
    
        public int cusotmerTabletID { get; set; }
        public string androidVersion { get; set; }
        public string cupID { get; set; }
        public string activationCode { get; set; }
        public string mark { get; set; }
        public string model { get; set; }
        public string comment { get; set; }
        public string creationDate { get; set; }
        public Nullable<int> regUserID { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakhsisTabletAndClientToConvention> TakhsisTabletAndClientToConvention { get; set; }
    }
}
