//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerComputers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customerComputers()
        {
            this.customerComputerLog = new HashSet<customerComputerLog>();
            this.TakhsisTabletAndClientToConvention = new HashSet<TakhsisTabletAndClientToConvention>();
        }
    
        public int customerComputerID { get; set; }
        public string userFullName { get; set; }
        public string macAddress { get; set; }
        public string IPValid { get; set; }
        public string comment { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
        public string NameActiveStatus { get; set; }
        public Nullable<bool> IsServer { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customerComputerLog> customerComputerLog { get; set; }
        public virtual operatingSystem operatingSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakhsisTabletAndClientToConvention> TakhsisTabletAndClientToConvention { get; set; }
    }
}
