//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sacEntities : DbContext
    {
        public sacEntities()
            : base("name=sacEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public virtual DbSet<AttachmentKind> AttachmentKind { get; set; }
        public virtual DbSet<companyTask> companyTask { get; set; }
        public virtual DbSet<ContactType> ContactType { get; set; }
        public virtual DbSet<convention> convention { get; set; }
        public virtual DbSet<conventionDuration> conventionDuration { get; set; }
        public virtual DbSet<ConventionLog> ConventionLog { get; set; }
        public virtual DbSet<ConventionProductProperty> ConventionProductProperty { get; set; }
        public virtual DbSet<conventionType> conventionType { get; set; }
        public virtual DbSet<customerComputerLog> customerComputerLog { get; set; }
        public virtual DbSet<customerComputers> customerComputers { get; set; }
        public virtual DbSet<CustomerTablets> CustomerTablets { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<operatingSystem> operatingSystem { get; set; }
        public virtual DbSet<Phase> Phase { get; set; }
        public virtual DbSet<postpone> postpone { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<ProductProperty> ProductProperty { get; set; }
        public virtual DbSet<project> project { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<ShareProjectToDepartment> ShareProjectToDepartment { get; set; }
        public virtual DbSet<TakhsisTabletAndClientToConvention> TakhsisTabletAndClientToConvention { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<taskAttachment> taskAttachment { get; set; }
        public virtual DbSet<taskComment> taskComment { get; set; }
        public virtual DbSet<taskLog> taskLog { get; set; }
        public virtual DbSet<taskPriority> taskPriority { get; set; }
        public virtual DbSet<taskRefer> taskRefer { get; set; }
        public virtual DbSet<taskRelationType> taskRelationType { get; set; }
        public virtual DbSet<taskStatus> taskStatus { get; set; }
        public virtual DbSet<taskSubject> taskSubject { get; set; }
        public virtual DbSet<taskTimeConsumption> taskTimeConsumption { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<UserKind> UserKind { get; set; }
        public virtual DbSet<userRole> userRole { get; set; }
        public virtual DbSet<select_all_data> select_all_data { get; set; }
    }
}
