//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperty
    {
        public int ProductPropertyID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string PropertyName { get; set; }
        public Nullable<decimal> PropertyPrice { get; set; }
    }
}
