//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class select_all_data
    {
        public string taskCreationDate { get; set; }
        public string taskDoneDate { get; set; }
        public string comment { get; set; }
        public string MONAME { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> taskDoneUserID { get; set; }
        public Nullable<int> conventionTypeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<int> departmentID { get; set; }
        public Nullable<int> phaseID { get; set; }
        public Nullable<int> projectID { get; set; }
        public Nullable<int> tedad { get; set; }
        public string lastcontract { get; set; }
        public string name { get; set; }
        public Nullable<int> countOfSystem { get; set; }
        public Nullable<int> SHMO { get; set; }
    }
}
