//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskTimeConsumption
    {
        public int timeConsumptionID { get; set; }
        public string fromDate { get; set; }
        public string fromTime { get; set; }
        public string toDate { get; set; }
        public string toTime { get; set; }
        public string comment { get; set; }
    
        public virtual task task { get; set; }
        public virtual user user { get; set; }
    }
}
