//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class taskLog
    {
        public int editTaskID { get; set; }
        public string fromReferingNO { get; set; }
        public string toReferingNO { get; set; }
        public string fromDueDate { get; set; }
        public string toDueDate { get; set; }
        public string fromCommnt { get; set; }
        public string toComment { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual CUSTOMERS CUSTOMERS1 { get; set; }
        public virtual task task { get; set; }
        public virtual taskPriority taskPriority { get; set; }
        public virtual taskPriority taskPriority1 { get; set; }
        public virtual taskRelationType taskRelationType { get; set; }
        public virtual taskRelationType taskRelationType1 { get; set; }
        public virtual taskSubject taskSubject { get; set; }
        public virtual taskSubject taskSubject1 { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
    }
}
