//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public task()
        {
            this.postpone = new HashSet<postpone>();
            this.taskAttachment = new HashSet<taskAttachment>();
            this.taskComment = new HashSet<taskComment>();
            this.taskLog = new HashSet<taskLog>();
            this.taskRefer = new HashSet<taskRefer>();
            this.taskTimeConsumption = new HashSet<taskTimeConsumption>();
        }
    
        public int taskID { get; set; }
        public Nullable<int> taskSubjectID { get; set; }
        public Nullable<int> taskAttachmentID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string taskCreationDate { get; set; }
        public string taskCreationTime { get; set; }
        public string taskDoneDate { get; set; }
        public string taskDoneTime { get; set; }
        public string DueDate { get; set; }
        public string DueTime { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string comment { get; set; }
        public Nullable<int> parentTaskID { get; set; }
        public string followingNO { get; set; }
        public string ReferNO { get; set; }
        public Nullable<int> currentDepartmentID { get; set; }
        public Nullable<int> PriorityID { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual convention convention { get; set; }
        public virtual Phase Phase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<postpone> postpone { get; set; }
        public virtual project project { get; set; }
        public virtual taskRelationType taskRelationType { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taskAttachment> taskAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taskComment> taskComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taskLog> taskLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taskRefer> taskRefer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<taskTimeConsumption> taskTimeConsumption { get; set; }
    }
}
