//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPCRMAtiran
{
    using System;
    using System.Collections.Generic;
    
    public partial class userRole
    {
        public int UserRollID { get; set; }
        public Nullable<int> RollID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual companyTask companyTask { get; set; }
        public virtual department department { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual project project { get; set; }
        public virtual user user { get; set; }
    }
}
